remote_theme: pages-themes/midnight@v0.2.0
collections:
  posts:
    permalink: "/blogs/:year/:month/:day/:title/"
    output: true
plugins:
- jekyll-remote-theme
- jekyll-gist
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
exclude:
- README.md
